version: '3'
services:
  node-app:
    build: .
    image: web3guardian-node:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: ["npx", "ts-node", "src/bot.ts"]
  redis:
    image: "redis:alpine"
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]  # PONG if everything is alright :D
      interval: 1s
      timeout: 3s
      retries: 30
