version: '3'
services:
  node-app:
    build: .
    image: web3guardian-node:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command:  # install any new packages since last build then start the app
      - sh
      - -c
      - |
        npm install
        npm start
  redis:
    image: "redis:alpine"
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]  # PONG if everything is alright :D
      interval: 1s
      timeout: 3s
      retries: 30
      